branch-defaults:
  main:
    environment: stt-prod
environment-defaults:
  stt-demo4:
    branch: null
    repository: null
global:
  application_name: stt-tool
  default_ec2_keyname: null
  default_platform: Node.js 24 running on 64bit Amazon Linux 2023
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
