branch-defaults:
  main:
    environment: stt-demo4
    group_suffix: null
environment-defaults:
  stt-demo:
    branch: null
    repository: null
global:
  application_name: stt-tool
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 24
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
